version: 2

models:
  - name: fact_page_views
    description: "a fact table for page views from events"
    columns:
      - name: event_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: session_id
        description: "each user web session"
        tests:
          - not_null