version: 2

models:
  - name: fact_user_sessions
    description: "a fact table for page views from events"
    columns:
      - name: session_guid
        description: "The primary key for this table"
        tests:
          - not_null
    