version: 2

models:
  - name: fact_page_views
    description: "total page views per user-session level"
    tests:
      - dbt_expectations.expect_compound_columns_to_be_unique:
          column_list: ["session_guid", "user_guid"]
          ignore_row_if: "any_value_is_missing" 
      
    columns:
       - name: event_type
         tests:
          - accepted_values:
              values: ['page_view']
              config:
                severity: warn