version: 2

models:
  - name: fact_orders
    description: "a fact table for orders"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null